/* Copyright 2015 Yahoo Inc. */
/* Licensed under the terms of the 3-Clause BSD license. See LICENSE file in the project root for details. */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniContextAccess */

#ifndef _Included_jni_JniContextAccess
#define _Included_jni_JniContextAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniContextAccess
 * Method:    createContext
 * Signature: (I)Ljni/JniContext;
 */
JNIEXPORT jobject JNICALL Java_jni_JniContextAccess_createContext
  (JNIEnv *, jclass, jint);

/*
 * Class:     jni_JniContextAccess
 * Method:    execute
 * Signature: (Ljni/JniContext;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_JniContextAccess_execute
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jni_JniContextAccess
 * Method:    release
 * Signature: (Lyjava/jni/cleaner/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jni_JniContextAccess_release
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jni_JniContextAccess
 * Method:    getLeakIndex
 * Signature: (Lyjava/jni/cleaner/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_jni_JniContextAccess_getLeakIndex
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
